In [1]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
# from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
# from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("titanic.csv")


In [3]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)
df


,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,34.5,0,0,7.8292,Q
1,1,3,female,47.0,1,0,7.0000,S
2,0,2,male,62.0,0,0,9.6875,Q
3,0,3,male,27.0,0,0,8.6625,S
4,1,3,female,22.0,1,1,12.2875,S
...,...,...,...,...,...,...,...,...
413,0,3,male,NaN,0,0,8.0500,S
414,1,1,female,39.0,0,0,108.9000,C
415,0,3,male,38.5,0,0,7.2500,S
416,0,3,male,NaN,0,0,8.0500,S


In [4]:
df.isnull().sum()
# df.head()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [16]:
df.fillna({"Age": df["Age"].mean()}, inplace=True)

In [5]:
df.isnull().sum()
df



,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,34.5,0,0,7.8292,Q
1,1,3,female,47.0,1,0,7.0000,S
2,0,2,male,62.0,0,0,9.6875,Q
3,0,3,male,27.0,0,0,8.6625,S
4,1,3,female,22.0,1,1,12.2875,S
...,...,...,...,...,...,...,...,...
413,0,3,male,NaN,0,0,8.0500,S
414,1,1,female,39.0,0,0,108.9000,C
415,0,3,male,38.5,0,0,7.2500,S
416,0,3,male,NaN,0,0,8.0500,S


In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns="Survived"),df['Survived'],test_size=0.2,random_state=42)
X_train.isnull().sum()

Pclass       0
Sex          0
Age         72
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [21]:
si_fare=SimpleImputer()
X_train_fare=si_fare.fit_transform(X_train[["Fare"]])
X_test_fare=si_fare.transform(X_test[["Fare"]])
X_train_fare


array([[ 13.        ],
       [ 31.5       ],
       [ 10.7083    ],
       [ 82.2667    ],
       [ 10.5       ],
       [  7.05      ],
       [ 26.        ],
       [ 21.075     ],
       [ 79.2       ],
       [  9.225     ],
       [  7.925     ],
       [ 46.9       ],
       [ 18.        ],
       [ 47.1       ],
       [  7.75      ],
       [ 12.35      ],
       [  7.775     ],
       [  7.75      ],
       [  7.05      ],
       [  8.6625    ],
       [  7.925     ],
       [ 25.4667    ],
       [  7.8958    ],
       [ 10.5       ],
       [  7.225     ],
       [  7.725     ],
       [  7.8958    ],
       [ 12.35      ],
       [ 14.5       ],
       [  0.        ],
       [134.5       ],
       [  6.4375    ],
       [ 61.9792    ],
       [ 29.        ],
       [ 27.75      ],
       [ 21.        ],
       [  8.7125    ],
       [ 26.        ],
       [  8.6625    ],
       [ 21.6792    ],
       [  7.8542    ],
       [ 93.5       ],
       [ 75.2417    ],
       [  7

In [22]:
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex=ohe_sex.fit_transform(X_train[["Sex"]])
X_train_embarked=ohe_embarked.fit_transform(X_train[["Embarked"]])
print(X_train_sex[3:15,0:2])
print(X_train_sex.shape)
X_test_sex=ohe_sex.transform(X_test[['Sex']])
X_test_embarked=ohe_embarked.transform(X_test[['Embarked']])
print(X_train_embarked.shape)


[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
(334, 2)
(334, 3)


In [23]:
X_train_rem=X_train.drop(columns=['Fare','Sex','Embarked'])
print(X_train_rem.shape)
X_test_rem=X_test.drop(columns=['Fare','Sex','Embarked'])

(334, 4)


In [24]:
X_train_transformed=np.concatenate((X_train_rem,X_train_fare,X_train_embarked,X_train_sex),axis=1)
X_test_transformed=np.concatenate((X_test_rem,X_test_fare,X_test_embarked,X_test_sex),axis=1)
X_train_transformed

array([[ 2., 32.,  0., ...,  1.,  0.,  1.],
       [ 2., 24.,  2., ...,  1.,  0.,  1.],
       [ 2., nan,  0., ...,  0.,  0.,  1.],
       ...,
       [ 1., 46.,  0., ...,  0.,  0.,  1.],
       [ 2., 24.,  0., ...,  1.,  0.,  1.],
       [ 3., nan,  0., ...,  0.,  0.,  1.]])

In [171]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,Y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [172]:
y_pred=clf.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [175]:
accuracy=accuracy_score(Y_test,y_pred)
accuracy

1.0

In [176]:
import pickle 


In [179]:
pickle.dump(ohe_sex,open('model/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('model/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('model/clf.pkl','wb'))